AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  singed
  Sample SAM Template for singed

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
Resources:
  MainFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: /app.lambdaHandler
      Runtime: nodejs14.x
      Role: arn:aws:iam::164620743841:role/lambda-execution-role # Pre-existing role
      Environment:
        Variables:
          TEST_2: Value345
      Layers:
        - !Ref DepLayer
      Events:
        SavePost:
          Type: HttpApi
          Properties:
            Method: post
            Path: /post
        GetIndex:
          Type: HttpApi
          Properties:
            Method: get
            Path: /book
        Register:
          Type: HttpApi
          Properties:
            Method: post
            Path: /register
        CheckLogin:
          Type: HttpApi
          Properties:
            Method: post
            Path: /register/checkLogin

  DepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: singed-app-dependencies
      Description: Dependencies for  singed-app
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
